[package]
name = "gm"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies", "Hangbiao Zou (btwiuse)"]
description = "Gear Multitoken"

[dependencies]
gstd = { git = "https://github.com/btwiuse/gear.git", features = ["debug"] }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
num-traits = { version = "0.2", default-features = false }
primitive-types = { version = "0.12.0", default-features = false, features = ["scale-info"] }

[dev-dependencies]
gtest = { git = "https://github.com/btwiuse/gear.git" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/btwiuse/gear.git" }

[workspace]
members = [
  "labs/*",
]
